
project_id = "xccidvoxhpgcnwinnyin"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true
enable_email_change_confirmations = true
enable_phone_confirmations = false
enable_phone_change_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[edge_functions]
enabled = true
port = 54330

[functions.send-event-management-email]
verify_jwt = false

[functions.create-common-good-payment]
verify_jwt = false

[functions.post-common-good-message]
verify_jwt = false

[functions.get-common-good-totals]
verify_jwt = false

[functions.send-cinema-ticket-email]
verify_jwt = false

[functions.save-push-subscription]
verify_jwt = false

[functions.delete-push-subscription]
verify_jwt = false

[functions.track-notification-event]
verify_jwt = false

[functions.track-push-optin]
verify_jwt = false

[functions.backfill-push-user-links]
verify_jwt = false

[functions.get-enabled-users-count]
verify_jwt = false

[functions.link-push-subscription]
verify_jwt = false

[functions.send-push]
verify_jwt = true

[functions.track-notification-click]
verify_jwt = false

# New functions
[functions.upsert-notification]
verify_jwt = true

[functions.process-scheduled-notifications]
verify_jwt = false

[functions.process-receipt-streak]
verify_jwt = true

[functions.get-streak-dashboard]
verify_jwt = true

[functions.claim-streak-reward]
verify_jwt = true

[functions.calculate-weekly-streaks]
verify_jwt = false

[functions.webauthn-register-options]
verify_jwt = false

[functions.webauthn-register-verify]
verify_jwt = false

[functions.webauthn-auth-options]
verify_jwt = false

[functions.webauthn-auth-verify]
verify_jwt = false

[functions.webauthn-create-session]
verify_jwt = false

[functions.clear-webauthn-data]
verify_jwt = false

[functions.start-membership-link]
verify_jwt = false

[functions.verify-membership-link]
verify_jwt = false

[functions.check-membership]
verify_jwt = false

[functions.admin-wipe-webauthn]
verify_jwt = false

[functions.loyalty-get-active-card]
verify_jwt = false

[functions.resolve-notification-personalization]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-welcome-emails-batch]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

# Mailchimp sync functions
[functions.sync-to-mailchimp]
verify_jwt = true

[functions.test-mailchimp-sync]
verify_jwt = false

[functions.manual-sync-test]
verify_jwt = false

[functions.mailchimp-batch-sync]
verify_jwt = true

[functions.mailchimp-full-sync]
verify_jwt = true

[functions.mailchimp-reconciliation-sync]
verify_jwt = true

[functions.check-vapid-config]
verify_jwt = false

[functions.test-push-debug]
verify_jwt = false

[functions.simple-push-test]
verify_jwt = false


[functions.calendly-webhook]
verify_jwt = false

[functions.member-analytics]
verify_jwt = true

[functions.test-function]
verify_jwt = false

[functions.advanced-analytics]
verify_jwt = true

[functions.member-deep-dive]
verify_jwt = true

[functions.campaign-manager]
verify_jwt = true

[functions.seed-baseline-grace-week]
verify_jwt = true

[functions.apply-grace-week]
verify_jwt = true

[functions.create-wallet-pass]
verify_jwt = false

[functions.revoke-wallet-pass]
verify_jwt = true

[functions.generate-proposal-pdf]
verify_jwt = true

[functions.proposal-redirect]
verify_jwt = false

[functions.send-proposal-email]
verify_jwt = true

[functions.proposal-latest]
verify_jwt = false

[functions.generate-contract-pdf]
verify_jwt = true

[functions.send-contract-email]
verify_jwt = true

[functions.generate-beo-pdf]
verify_jwt = true

[functions.send-beo-email]
verify_jwt = true

[functions.management-ai-assistant]
verify_jwt = true

[functions.generate-invoice-pdf]
verify_jwt = true

[functions.get-beo-signed-url]
verify_jwt = false

[functions.proxy-beo-pdf]
verify_jwt = false

[functions.extract-document-content]
verify_jwt = true

[functions.update-document-content]
verify_jwt = true

[functions.reextract-document]
verify_jwt = true

[functions.analyze-feedback-sentiment]
verify_jwt = true

[functions.generate-feedback-report]
verify_jwt = true

[functions.generate-daily-feedback-report]
verify_jwt = false

[functions.chat-ai-cleo]
verify_jwt = true

[functions.create-management-user]
verify_jwt = true

[functions.web-search-proxy]
verify_jwt = true

[functions.event-enquiry-chat]
verify_jwt = false

[functions.convert-enquiry-to-lead]
verify_jwt = false

[functions.generate-event-proposal]
verify_jwt = false

[functions.client-portal-data]
verify_jwt = false

[functions.client-send-message]
verify_jwt = false

[functions.client-upload-file]
verify_jwt = false

