project_id = "szokkwlleqndyiojhsll"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.create-cb-wallet-pass]
    verify_jwt = false
  [functions.verify-cb-member]
    verify_jwt = false
